version: '3.8'

networks:
  chatws_net:
    driver: bridge

services:

# chatws - Backend
  backend:
    image: chatws-server
    container_name: chatws-server
    volumes:
      - /c/Users/thyag/Workspaces/Java/Websockets/chat/chatws:/app/server/chatws
    networks:
      - chatws_net
    build:
      context: chatws
      dockerfile: ./Dockerfile
    ports:
      - 8085:8085

# chatws - Frontend
  ui:
    container_name: chatws-ui
    image: chatws-ui
    networks:
      - chatws_net
    build:
      context: frontend
      dockerfile: ./Dockerfile
    volumes:
      - /c/Users/thyag/Workspaces/Java/Websockets/chat/frontend:/app/chatws/frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

# Elasticsearch
  e:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      # - ES_PROTOCOL="http"
      # - xpack.security.enabled=false
      # - ELASTIC_APM_VERIFY_SERVER_CERT=false
      # - XPACK_LICENSE_SELF_GENERATED_TYPE="basic"
      # - node.max_local_storage_nodes=2
    volumes:
      - /c/Users/thyag/Workspaces/Java/Websockets/chat/elasticsearch:/usr/share/elasticsearch/data:rw
      - /c/Users/thyag/Workspaces/Java/Websockets/chat/logs/elasticsearch:/usr/share/elasticsearch/logs,rw
    networks:
      - chatws_net
    ports:
      - 9200:9200
      - 9300:9300
    depends_on:
      - backend

# Kibana
  k:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - chatws_net
    ports:
      - 5601:5601
    depends_on:
      - e